packages:
  - 'apps/*'
  - 'packages/*'
supportedArchitectures:
  os:
    - win32
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  argon2: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
